---

- hosts: devlinux
  user: velocity
  become: yes
  connection: ssh

  tasks:
    - name: install HTTPD
      action: yum name=httpd state=present

    - name: start HTTPD
      action: service name=httpd state=started

    - name: deploy index
      action: copy src=index.html dest=/var/www/html/
