---  #Defining and calling variable

- hosts: devlinux
  user: velocity
  become: yes
  connection: ssh

  vars:
    pkgname: httpd
    index_path: /var/www/html/

  tasks:
    - name: install httpd
      action: yum name="{{pkgname}}" state=present

    - name: start httpd
      action: service name="{{pkgname}}" state=started

    - name: deploy index
      action: copy src=index.html dest="{{index_path}}"
